# SurfaceDuo2Pkg CI build on VSTS

trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md
    - LICENSE

pool:
  vmImage: 'Ubuntu-latest'
  
steps:
- script: sudo apt update 
  displayName: 'Update APT sources'

# Travis have this by default, because we preinstalled build-essentials
- script: sudo apt install uuid-dev flex bison
  displayName: 'Install VSTS dependencies'

# Fix-up directory link for VSTS, force replace current reference
- script: sudo ln -sfn $(pwd) ../SurfaceDuo2Pkg
  displayName: 'Fix directory links'

# Build iASL tool from repository
# Eventually we will just install prepackaged version
# - script: git clone https://github.com/acpica/acpica acpica-tools
#   displayName: 'Checkout ACPICA tools repository'

# - script: cd acpica-tools && make clean && make && sudo make install && cd ..
#   displayName: 'Build and install ACPICA tools'

- script: chmod +x ./setup_env.sh && sudo ./setup_env.sh
  displayName: 'Prepare pre-build environment, phase 0'

- script: pip install --upgrade -r ./pip-requirements.txt
  displayName: 'Prepare pre-build environment, phase 1'

- script: chmod +x ./build_releaseinfo.ps1 && ./build_releaseinfo.ps1
  displayName: 'Prepare pre-build environment, phase 2'

- script: chmod +x ./build_uefi.sh && ./build_uefi.sh
  displayName: 'UEFI build'

- script: chmod +x ./build.sh && ./build.sh
  displayName: 'UEFI boot image build'

# Publish UEFI (1 target)
- task: PublishBuildArtifacts@1
  displayName: 'Publish UEFI build (Surface Duo 2)'
  inputs:
    pathtoPublish: ./uefi.img
    artifactName: SM8350 UEFI (Surface Duo 2)

# Publish Boot (1 target)
- task: PublishBuildArtifacts@1
  displayName: 'Publish Boot build (Surface Duo 2)'
  inputs:
    pathtoPublish: ./boot.img
    artifactName: SM8350 Boot (Surface Duo 2)